warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery"
]

allow = [
    "clippy::module_name_repetitions",
    "clippy::too_many_lines",
    "clippy::multiple_crate_versions"
]

deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::unimplemented",
    "clippy::panic",
    "clippy::todo"
]

line_length = 100
cognitive-complexity-threshold = 25